// PDF generation utilities
// Note: For production, you would use a library like jsPDF or html2pdf.js
// This is a simplified implementation

export interface PDFOptions {
  includeTableOfContents: boolean;
  includePageNumbers: boolean;
  includeHeader: boolean;
  includeFooter: boolean;
}

export async function generatePDF(
  markdown: string,
  title: string,
  options: PDFOptions
): Promise<Blob> {
  // Convert markdown to HTML
  const html = await markdownToHTML(markdown);

  // Apply PDF styling
  const styledHTML = applyPDFStyles(html, title, options);

  // In a real implementation, use html2pdf or similar
  // For now, create a simple HTML blob
  const blob = new Blob([styledHTML], { type: 'text/html' });

  return blob;
}

function markdownToHTML(markdown: string): string {
  // Simple markdown to HTML converter
  // In production, use a library like marked or remark
  let html = markdown;

  // Headers
  html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^\)]+)\)/g, '<a href="$2">$1</a>');

  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Lists
  html = html.replace(/^\- (.+$)/gim, '<li>$1</li>');
  html = html.replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');

  // Horizontal rules
  html = html.replace(/^---$/gim, '<hr/>');

  // Paragraphs
  html = html.replace(/\n\n/g, '</p><p>');
  html = '<p>' + html + '</p>';

  // Tables (basic support)
  html = html.replace(/\|(.+)\|/g, (match) => {
    const cells = match.split('|').filter(cell => cell.trim());
    return '<tr>' + cells.map(cell => `<td>${cell.trim()}</td>`).join('') + '</tr>';
  });

  return html;
}

function applyPDFStyles(html: string, title: string, options: PDFOptions): string {
	  const header = options.includeHeader ? `
	    <header style="text-align: center; border-bottom: 2px solid #f59e0b; padding-bottom: 20px; margin-bottom: 30px;">
	      <img src="/images/brand/mango-logo-horizontal-white.png" alt="Mango Law" style="height: 60px; margin-bottom: 10px;" />
	      <h1 style="color: #1e293b; margin: 0;">${title}</h1>
	    </header>
	  ` : '';

  const footer = options.includeFooter ? `
    <footer style="text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 40px; color: #64748b; font-size: 12px;">
      <p>Generated by Mango Law Admin Dashboard | mangolaw.com</p>
    </footer>
  ` : '';

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Inter', -apple-system, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      background: white;
    }

    h1 {
      font-size: 2.5em;
      color: #0f172a;
      margin-bottom: 0.5em;
      border-bottom: 3px solid #f59e0b;
      padding-bottom: 0.3em;
      page-break-after: avoid;
    }

    h2 {
      font-size: 2em;
      color: #1e293b;
      margin-top: 1.5em;
      margin-bottom: 0.75em;
      page-break-after: avoid;
    }

    h3 {
      font-size: 1.5em;
      color: #334155;
      margin-top: 1.25em;
      margin-bottom: 0.5em;
      page-break-after: avoid;
    }

    p {
      margin-bottom: 1em;
      text-align: justify;
    }

    ul, ol {
      margin-left: 2em;
      margin-bottom: 1em;
    }

    li {
      margin-bottom: 0.5em;
    }

    code {
      background: #f1f5f9;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 0.9em;
    }

    pre {
      background: #1e293b;
      color: #e2e8f0;
      padding: 1em;
      border-radius: 6px;
      overflow-x: auto;
      margin-bottom: 1em;
      page-break-inside: avoid;
    }

    pre code {
      background: transparent;
      padding: 0;
      color: inherit;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 1.5em;
      page-break-inside: avoid;
    }

    td {
      border: 1px solid #e2e8f0;
      padding: 0.75em;
    }

    tr:nth-child(even) {
      background: #f8fafc;
    }

    hr {
      border: none;
      border-top: 1px solid #cbd5e1;
      margin: 2em 0;
    }

    a {
      color: #f59e0b;
      text-decoration: none;
    }

    a:hover {
      text-decoration: underline;
    }

    strong {
      font-weight: 600;
      color: #0f172a;
    }

    @media print {
      body {
        padding: 20px;
      }

      h1, h2, h3 {
        page-break-after: avoid;
      }

      pre, table {
        page-break-inside: avoid;
      }

      ${options.includePageNumbers ? `
      @page {
        margin: 1in;
        @bottom-right {
          content: "Page " counter(page);
        }
      }
      ` : ''}
    }
  </style>
</head>
<body>
  ${header}
  ${html}
  ${footer}
</body>
</html>
  `;
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
